spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
logging:
  level:
    web: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR