spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
logging:
  level:
    web: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
springdoc:
  override-with-generic-response: false